config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  get 'now', to: "static_pages#now"
  get 'twentyseventeen', to: "static_pages#twentyseventeen"
  get 'cities', to: "static_pages#cities"
  get 'books', to: "static_pages#books"
  get 'email', to: "static_pages#email"
  get 'attribution', to: "static_pages#attribution"
  resources :posts
  get '*path' => redirect('/')

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]


  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save
      redirect_to @post, notice: "Hellz yeah, Gonzalo. Your article was successfully saved."
    else
      render 'new', notice: "Oh no, Gonzalo. I was unable to save your post."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Yeah, your article was successfully saved"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

private

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>@gonsanchezs</title>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto+Slab:400,700|Roboto:400,700|Merriweather:400,700|Merriweather+Sans:400,700" rel="stylesheet">
  <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
  <link href="https://file.myfontastic.com/n6vo44Re5QaWo8oCKShBs7/icons.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=devide-width, initial-scale=1">
</head>
<body>

 <!-- Collect the nav links, forms, and other content for toggling -->

 <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script>
    $(function(){
        $('a').each(function(){
            if ($(this).prop('href') == window.location.href) {
                $(this).addClass('current'); $(this).parents('li').addClass('current');
            }
        });
    });
</script>

  <script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip(); 
    });
  </script>

  <!-- 

   <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <nav class="header--nav col-md-6 column__intro">
    <ul class="nav navbar-nav"> 
      <li><%= link_to 'Home', root_path, :class => "header--nav--link"  %></li>
      <li><%= link_to 'Now', now_path, :class => "header--nav--link"  %></li>
      <li><a class="header--nav--link" href="books.html">Books</a></li>
      <li><a class="header--nav--link" href="cities.html">Cities</a></li>
      <% if user_signed_in? %>
      <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete, :class => "header--nav--link" %></li>
      <% end %>
      </ul>
    </nav>

  </header>

  <% if notice %>
    <div class="content clearfix">
      <p class="notice"><%= notice %></p>
    </div>
  <% elsif alert %>
    <div class="content clearfix">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

  </div>

  !-->

<%= yield %>

<br />

<footer class="footer col-md-6">
  <div class="container">
    <nav class="footer--nav">
      <p class="footer--note">v0.1 in Reyjkavík, v0.2 in Paris</p>
    </nav>
  </div>
</footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <% if @post.errors.any? %>
    <h2> <%- pluralize(@post.errors.count, "error") %> prevented this post from saving.</h2>
      <ul>
        <%= @post.errors.full_messages each do |message| %>
          <li><%= message %></li>
        <% end %>   
      </ul>
  <% end %>

  <%= f.label :title, "Your title - make it short and memorable" %><br />
  <%= f.text_field :title, :class => "title--box" %>

    <br />
    <br />

  <%= f.label :content, "Your bangin' article goes here" %><br />
  <%= f.text_area :content, :class => "text--box" %>

    <br />
    <br />

   <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<div class="content clearfix">
  <div class="article--wrapper col-xs-12">

    <h2 class="article--title">Edit post</h2>
    <%= render 'form' %>

  </div>
</div>

app/views/posts/index.html.erb
<div class="content clearfix">
  <div class="section--wrapper col-xs-12">
    <h1 class="section--title">Random Thoughts</h1>
    <div class="section--body">
      <h4>This is where I organize and dump my personal thoughts.</h4>
    </div>

    <% @posts.each do |post| %>
      <div class="page--posts">
        <div class="post">
          <h2 class="post--title"><a class="post--title__link" href="#"><%= link_to post.title, post %></a></h2>
          <p class="post--date"><%= post.created_at.strftime("%B %Y") %></p>  
        </div>
      </div>
    <% end %>
      <br />
    <%= will_paginate @posts, :class => 'digg_pagination' %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="content clearfix">
  <div class="article--wrapper col-xs-12">

<h2 class="article--title">Write a new post</h2>

<%= render 'form' %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="content clearfix">

  <div class="article--wrapper col-xs-12">

<h1 class="article--title"><%= @post.title %></h1>

<div class="article--body"> 
<%= markdown @post.content %> <br />
</div>

<% if user_signed_in? %>
  <div class="admin--links">
  <%= link_to "Edit", edit_post_path(@post) %>
  <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete thi post?" } %> 
  </div>
<% end %>

  </div>
</div>

app/views/static_pages/attribution.html.erb
<div class="content clearfix">
  <div class="article--wrapper col-xs-12">

<h1 class="article--title">Building an Attributin Model for EVELO</h1>

<div class="article--body"> 

<br />

<p>At EVELO, we are on consistently attempting to become more sophisticated with our marketing efforts. </p>

<p>As part of this effort, we moved away from the usual last click attribution model present in all Google Analytics reports.</p>
<p>As Avinash Kaushik [likes to say](https://www.kaushik.net/avinash/multi-channel-attribution-modeling-good-bad-ugly-models/) – *the only use for last click attribution now is to get you fired. Avoid it.*</p>
<p>He is right. This model is silly. It gives no weight to all the preceding actions a customer took. On top of that, the way we do business generates a couple of interesting challenges.</p>

<h2>First challenge – a sales team </h2>
<p>Due to the price point of our product ($2950 AOV), we act more as a B2B business than an eCommerce consumer company. In fact, 86% of our sales happen after some kind of interactions with our team, and those sales have an AOV $300 higher than the remaining 14%. This means people are more likely to buy (and spend more) if the speak to us. </p>
<p>The problem this causes is when our sales team places an order over the phone, sends a cart link to the customer, or simply suggests the customer to head to evelo.com. </p>
<p>Why we know this? Not only we know our business, but if you look at Last Click attribution, most than 50% of our sales are attributed to *direct*.</p>

<%= image_tag '1-last-click.png' %>

<br />

<p>Yeah, fun. </p>
<p>A quick solution would be to use Last Non-Direct Click attribution. And in fact, when we play with this model, it looks a lot better.</p>

<%= image_tag '1-last-non-direct.png' %>

<br />

<p>But this generates another problem... </p>

<h2>Second channel – discovery is being unattributed </h2>

<p>Discovery is being under attributed, so Adwords ROI sucks.</p>
<p>As you can see, if we look at Adwords numbers on a last click basis, our branded campaigns look amazing. </p>


<%= image_tag '2-branded.png' %>

<br />

<p>But are they? Or are we seeing those numbers because visitors, after doing research, google 'evelo' and click on one of our ads? If this is the case, we are attributing everything to the last campaign they see, but not that last one. </p>
<p>With this model, our average CAC for Adwords is $1k. But it's really not. </p>
<p>If we change the model to First Click Attribution, our unbranded campaigns start gaining traction. This means unbranded search has a huge first interaction impact (roughly 15x the last click model)</p>

<%= image_tag '2-unbranded.png' %>

<br />

<p>Better. But still not good. The challenge is that we aren't attributing a single thing to last clicks, which is essentially, the final action previous to a conversion. </p>

<h2>Solution</h2>

<p>The solution would be to build a custom attribution model. The two main things we need to figure out is how to (a) under attributing direct, and (b) over attribute discovery. </p>
<p>This is how our new model look like now. </p>

<%= image_tag '3-attribution.png' %>

<br />

<p>A few interesting decisions. </p>

<ul>
<li><b>Position-based vs Timedecay.</b> With our current marketing channels, we needed to give proper attribution to discovery, specially for Adwords.</li>
<li><b>Conversion window.</b> We decided to go with  14 days, because most of our sales happen in that time period. </li>
<li><b>Giving direct a weight of 0.</b> By adding this custom rule, we are removing direct from last click attribution. Which means we are combinining position based model with the Non-direct Last Click model. Hopefully, this gives us the best of both worlds.</li>

</ul>

<p>It's not perfect, but it's a great place to start.</p>

  </div>



  </div>
</div>

app/views/static_pages/books.html.erb
<div class="content clearfix">
  <div class="section--wrapper col-xs-12 col-md-6 col-md-offset-3 column__intro">
    <h1 class="section--title">Interesting books</h1>
    <div class="section--body">
      <h4>I try to read as much as possible (although sometimes, Netflix gets in the way). Not everything I read is good but if it is, you'll find it here. A <i class="em em-book"></i> means it blew my mind in some way or another.</h4>
      <ul>
        <li>Ego is The Enemy</span> <i class="em em-book"></i></li>
        <li>The Obstacle is The Way</li>
        <li>Rework</span> <i class="em em-book"></i></li>
        <li>Remote</li>
        <li>Ready Player One</span> <i class="em em-book"></i></li>
        <li>The Subtle Art of Not Giving a Fuck</li>
        <li>Hooked: Building Habit Forming Products</li>
        <li>Sapiens</span> <i class="em em-book"></i></li>
        <li>The War of Art</li>
        <li>Bird by Bird</li>
        <li>Meditations</span> <i class="em em-book"></i></li>
        <li>Gang Leader for a Day</li>
        <li>My Life as an Experiment</li>
        <li>The Year of Living Biblically</li>
        <li>Provenance: How a Con Man and a Forger Rewrote the History of Modern Art</li>
        <li>How To Win Friends & Influence People</li>  
        <li>The Stand</span> <i class="em em-book"></i></li>
        <li>When The Lion Feeds Saga</li>      
        <li>Salem's Lot</li>
        <li>Lord of The Rings Trilogy</li>  
        <li>Harry Potter Saga</li>  
        <li>Barça: The Making of the Greatest Team in History</li>
        <li>More Money Than God</li>
        <li>We Are All Weird</li>
        <li>Founders at Work</span> <i class="em em-book"></i></li>
        <li>Predictably Irrational</li>
        <li>Freakonomics</li>
        <li>I'll Go Home Then; It's Warm and It has Chairs</li>
        <li>The Four Hour *</li>
        <li>The 22 Immutable Laws of Marketing</li>
        <li>Jony Ive: The Genius Behind Apple's Greatest Products</li>
        <li>The Hard Thing About Hard Things</li>
        <li>Product Design For the Web</li>
        <li>Zero to One</span> <i class="em em-book"></i></li>
        <li>Soccernomics</li>
        <li>Trust Me I'm Lying: Confessions of a Media Manipulation</li>
        <li>The Art of Learning: A Journey in the Pursuit of Excellence </li>
        <li>Permission Marketing: Turning Strangers Into Friends And Friends Into Customers </li>
        <li>The Adweek Copywriting Handbook</li>
        <li>Pep Guardiola: Another Way of Winning</li>
        <li>Steal Like an Artist</li>
        <li>The Subtle Art of Not Giving a Fuck</li>
        <li>Getting Real <i class="em em-book"></i></li>
        <li>Hooked - Building Habit Forming Products</li>
        <li>Shoe Dog</li>
        <li>A Guide to a Better Life <i class="em em-book"></i></li>
        <li>The Daily Stoic </li>
        <li>The City and the Stars</li>
        <li>The Fish That Ate the Whale</li>
        <li>The Year Without Pants</li>
        <li>A Guide to a Better Life</li>
        <li>Fluent Forever</li>
      </ul>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div>

    <div class="column col-xs-12 col-md-6 column__intro left-column">

      <h1 class="homepage--title">Gonz Sánchez</h2>
      <p class="homepage--intro">Growth & product guy, I can also design and code. Argentinean living in Paris, but flying around the world. <%= link_to 'Now', now_path  %>.</p>


      <h3>💻 Work</h3>
      <p class="homepage--intro">Previously Intern at <a href="https://foundersgrid.com">Foundersgrid</a>, Content Specialist at <a href="https://piktochart.com">Piktochart</a>, Director of Marketing at <a href="https://evelo.com">EVELO</a>, now <a href="https://themartec.com">freelancing</a>, <a href="https://thebrandery.com">mentoring startups</a>.

<p class="tags">
        <span class="foundation">Foundation</span> <br />
        <span class="individual--tag" id="base">behavioral psychology</span>
        <span class="individual--tag" id="base">data & analytics</span>
        <span class="individual--tag" id="base">design & UX</span>
        <span class="individual--tag" id="base">development</span>
        <span class="individual--tag" id="base">branding & positioning</span>
        <span class="individual--tag" id="base">management</span>
        <span class="individual--tag" id="base">automation</span>
</p>

<p class="tags">
        <span class="foundation">Marketing Skills</span> <br />
        <span class="individual--tag" id="marketing">CRO</span>
        <span class="individual--tag" id="marketing">excel modelling</span>
        <span class="individual--tag" id="marketing">funnel building</span>
        <span class="individual--tag" id="marketing">customer experience</span>
        <span class="individual--tag" id="marketing">customer lifecycle</span>
</p>

<p class="tags">
        <span class="foundation">Channel Specific</span> <br />
        <span class="individual--tag" id="channel">content & editorial</span>
        <span class="individual--tag" id="channel">email marketing</span>
        <span class="individual--tag" id="channel">facebook ads</span>
        <span class="individual--tag" id="channel">sales & lead gen</span>
        <span class="individual--tag" id="channel">social media</span>
</p>


      <h3>🚀 Projects</h3>
      <p class="homepage--intro">14,000 emails sent with <a href="http://minimize.email">Minimize Email</a>, +1000 subscribers on <a href="http://ecommercedai.ly">eCommerce Daily</a>, 8,000 users in 24 hours on <a href="http://blackfridaytech.co">Black Friday Tech</a>, <a href="http://diversitylist.co">Diversity List</a></p>

      <h3>🍺 Cool stuff about me</h3>
      <p class="homepage--intro">I read, fly, speak 4 languages, and lift heavy things. I don't mind the occasional burger or ramen. My body is <a href="https://www.mayoclinic.org/diseases-conditions/lymphedema/basics/definition/con-20025603">not symmetrical</a>, which led me to stoicism.</p>

      <h3>🏆 Success</h3>
      <p class="homepage--intro">College drop-out. Working remotely and doing OK. I could stop working and nothing would happen. Learned to code. <a href="https://www.shopperapproved.com/reviews/evelo.com/">Helped</a> hundreds of people. I'm healthy.</p>

      <h3>😰 Failures</h3>
      <p class="homepage--intro">College drop-out. 2 startups. Didn't prepare enough for my dream job's interview.</p>

      <h3>📱 Stay in touch</h3>
      <p class="homepage--intro"><a href="mailto: gonsanchezs@gmail.com">Email</a> or <a href="https://www.twitter.com/gonsanchezs">@gonsanchezs</a>.</p>

</div>

<div class="col-md-6 right-column">
</div>


  <!--
    <div class="col-xs-12 col-md-3 column" id="mobile-invisible">
      <h3 class="column--title">Thoughts</h3>

      <% @posts.each do |post| %>
        <h4 class="column--post-title"><%= link_to post.title, post, :class => "column--post-title__link" %></h4>
        <p class="column--post__date""> <%= post.created_at.strftime("%B %Y") %></p>
      <% end %>
      
    </div>


    <div class="col-xs-12 col-md-3 column" id="mobile-invisible">
      <h3 class="column--title">Case Studies</h3>
      <h4 class="column--post-title"><a class="column--post-title__link" href="#">Generating $150,000 with Email Automation</a></h4>
      <p class="column--post__date"">Coming soon</p>      
      <h4 class="column--post-title"><%= link_to 'Building an Attribution Model for EVELO', attribution_path, :class => "column--post-title__link" %></h4>
      <p class="column--post__date"">Friday April 10th</p>      
      <h4 class="column--post-title"><a class="column--post-title__link" href="https://www.viralsweep.com/casestudies/evelo/">Planning a Successful Giveaway</a></h4>
      <p class="column--post__date">Viralsweep.com</p>
    </div>
-->

  </div>

app/views/static_pages/now.html.erb
<div class="">
  <div class="section--wrapper column col-xs-12 col-md-6 column__intro left-column">
    <h1 class="homepage--title">What I'm doing now </h1>
    <div class="homepage--introy">
      <p>I'm currently freelancing, focusing on growth, product marketing and lead generation for B2B and eCommerce companies.</p>

      <p>To keep myself accountable, you can check my 2018 Resolutions and how I'm doing so far. My <%= link_to '2017 resolutions', twentyseventeen_path  %> are also public.</p>

      <h3>Health</h3>
      <p>A healthy body is a must for me. Last year I became stronger and more mobile. In 2018, I want to go with more technical movements </p>
      <ul>
        <li>Increase strenght and mobility - 70kg snatch.</li>
        <li>Increase skills - 5 muscleups.</li>
      </ul>

      <h3>Work</h3>
      <p>Work is a big part of my life, but I'm constantly reminding myself that it's not the only one. This year I'm graduating from little side projects to a real side business.</p>
        <ul>
          <li>Start a side business doing at least $2,000/month.</li> 
        </ul>

      <h3>Mindfullness</h3>
      <p>A healthy mind is as important as a healthy body. Last year, it was about travel and communication. 2018 won't be that different.</p>
        <ul>
          <li>Travel to 10 new countries.</li>
          <li>Climb Mount Kilimanjaro.</li>
          <li>Become fluent in french.</li>
        </ul>

      <p><i>This update was made on December 28, 2017.</i></p>
    </div>
  </div>
</div>

app/views/static_pages/twentyseventeen.html.erb
<div class="">
  <div class="section--wrapper column col-xs-12 col-md-6 column__intro left-column">
    <h1 class="homepage--title">2017 Resolutions</h1>
    <div class="homepage--introy">
      <p>To keep myself accountable, you can check my 2017 Resolutions and the end of year progress. My <%= link_to '2018 resolutions', now_path  %> are here.</p>

      <p>If there's one lesson learned, it's focus. In 2018 I'm going to limit the scope and number of resolutions.</p>

      <h3>Health</h3>
      <p>A healthy body is a must for me. In 2015 I improved my sleep and lost weight, and in 2017 I became stronger and more mobile.</p>
      <ul>
        <li>Increase strenght by increasing my 5 rep max - <s>Deadlift 110kg</s>, <s>front squat 80kg</s>, <s>push press 60kg</s>, <s>bench press 90kg</s>, <s>10 pull-ups</s>.</li>
        <li>Increase mobility - Gymnastics Body Intermediate Level. Update: slow progress, not as good as I hoped for but I didn't put in the work.</li>
      </ul>

      <h3>Work</h3>
      <p>Work is a big part of my life, but I'm constantly reminding myself that it's not the only one. </p>
        <ul>
          <li><s>Start a company or get a new job</s> Update: I quite my job, and started freelancing.</li> 
          <li><s>Start a side project.</s> <a href="http://minimize.email">Minimize Email</a>, <a href="http://ecommercedai.ly">eCommerceDaily</a>, <a href="http://diversitylist.co">Diversity List</a>, <a href="http://blackfridaytech.co">Black Friday Tech</a>. </li>
          <li>Code every week. Update: I suck at this, but I did build more stuff, specially towards the end of the year. Launching is a muscle that needs to be exercised.</li>
        </ul>

      <h3>Mindfullness</h3>
      <p>A healthy mind is as important as a healthy body. In 2016, I successfully got myself into stoicism. 2017 was about travel and communication.</p>
        <ul>
          <li>Travel to 10 new countries. Update: Japan, Czech Republic, Denmark, Belgium, Malta, Portugal, Finland, Estonia. I got super close, but for multiple personal reasons, I couldn't make it. It was a fun though.</li>
          <li><s>Become conversational in italian.</s> Update: L'italiano è un idioma bellisimo 🇮🇹 I'm focusing on french now.</li>
        </ul>

      <p><i>This update was made on December 28, 2017.</i></p>
    </div>
  </div>
</div>